/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XAccordion {
    }
    interface XAccordionItem {
        "class": string;
    }
    interface XAccordionItemPanel {
        "class": string;
        "isOpen": boolean;
    }
    interface XAccordionItemTrigger {
        "buttonClass": string;
        "class": string;
        "headingClass": string;
    }
}
export interface XAccordionItemTriggerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXAccordionItemTriggerElement;
}
declare global {
    interface HTMLXAccordionElement extends Components.XAccordion, HTMLStencilElement {
    }
    var HTMLXAccordionElement: {
        prototype: HTMLXAccordionElement;
        new (): HTMLXAccordionElement;
    };
    interface HTMLXAccordionItemElement extends Components.XAccordionItem, HTMLStencilElement {
    }
    var HTMLXAccordionItemElement: {
        prototype: HTMLXAccordionItemElement;
        new (): HTMLXAccordionItemElement;
    };
    interface HTMLXAccordionItemPanelElement extends Components.XAccordionItemPanel, HTMLStencilElement {
    }
    var HTMLXAccordionItemPanelElement: {
        prototype: HTMLXAccordionItemPanelElement;
        new (): HTMLXAccordionItemPanelElement;
    };
    interface HTMLXAccordionItemTriggerElement extends Components.XAccordionItemTrigger, HTMLStencilElement {
    }
    var HTMLXAccordionItemTriggerElement: {
        prototype: HTMLXAccordionItemTriggerElement;
        new (): HTMLXAccordionItemTriggerElement;
    };
    interface HTMLElementTagNameMap {
        "x-accordion": HTMLXAccordionElement;
        "x-accordion-item": HTMLXAccordionItemElement;
        "x-accordion-item-panel": HTMLXAccordionItemPanelElement;
        "x-accordion-item-trigger": HTMLXAccordionItemTriggerElement;
    }
}
declare namespace LocalJSX {
    interface XAccordion {
    }
    interface XAccordionItem {
        "class"?: string;
    }
    interface XAccordionItemPanel {
        "class"?: string;
        "isOpen"?: boolean;
    }
    interface XAccordionItemTrigger {
        "buttonClass"?: string;
        "class"?: string;
        "headingClass"?: string;
        "onXAccordionTriggerClicked"?: (event: XAccordionItemTriggerCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "x-accordion": XAccordion;
        "x-accordion-item": XAccordionItem;
        "x-accordion-item-panel": XAccordionItemPanel;
        "x-accordion-item-trigger": XAccordionItemTrigger;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "x-accordion": LocalJSX.XAccordion & JSXBase.HTMLAttributes<HTMLXAccordionElement>;
            "x-accordion-item": LocalJSX.XAccordionItem & JSXBase.HTMLAttributes<HTMLXAccordionItemElement>;
            "x-accordion-item-panel": LocalJSX.XAccordionItemPanel & JSXBase.HTMLAttributes<HTMLXAccordionItemPanelElement>;
            "x-accordion-item-trigger": LocalJSX.XAccordionItemTrigger & JSXBase.HTMLAttributes<HTMLXAccordionItemTriggerElement>;
        }
    }
}
